import Foundation
import CodeContextKitCore
import CodeContextKitStorage

/// Generates architectural summaries and "Project DNA" for agent memory files (CLAUDE.md/GEMINI.md).
public final class Summarizer {
    private let db: Database
    
    public init(db: Database) {
        self.db = db
    }
    
    /// Generates a "Project DNA" snippet based on repository analysis.
    public func generateProjectDNA() throws -> String {
        let stats = try db.getStats()
        let topSymbols = try db.getTopReferencedSymbols(limit: 15)
        let recentFiles = try db.getRecentlyChangedFiles(limit: 10)
        
        var output = "## 🧬 Project DNA (Generated by CCKit)\n\n"
        
        // 1. Core Architecture
        output += "### Core Architecture & Key Symbols\n"
        output += "This project consists of \(stats["symbolCount"] ?? 0) symbols across \(stats["fileCount"] ?? 0) files.\n"
        output += "Key types and high-traffic symbols include:\n"
        for (name, count) in topSymbols {
            output += "- `\(name)` (\(count) references)\n"
        }
        output += "\n"
        
        // 2. Tech Stack & Languages
        if let kindCounts = stats["kindCounts"] as? [String: Int] {
            output += "### Symbol Breakdown\n"
            let sortedKinds = kindCounts.sorted { $0.value > $1.value }
            for (kind, count) in sortedKinds.prefix(8) {
                output += "- **\(kind)**: \(count)\n"
            }
            output += "\n"
        }
        
        // 3. Recent Activity Focus
        output += "### Recent Focus Areas\n"
        output += "The following files have been recently modified or indexed:\n"
        for file in recentFiles {
            let fileName = (file.path as NSString).lastPathComponent
            output += "- `\(fileName)` (\(file.path))\n"
        }
        output += "\n"
        
        output += "---\n"
        output += "*Tip: Copy this into your CLAUDE.md or GEMINI.md to give agents an instant architectural head start.*"
        
        return output
    }
}
